// ============================================================
// HYPERCOMMERCE — AI Recommendation Service
// Two-tower architecture: collaborative + content-based hybrid.
//
// Algorithm stack:
// 1. Collaborative filtering: ALS matrix factorization embeddings
// 2. Content-based: product embedding similarity
// 3. Cold start: popularity fallback + onboarding quiz
// 4. Context: time-of-day, device, location boosts
// 5. Freshness: decay older interactions
// 6. Business rules: margin boost, seller agreements
//
// Infrastructure:
// - User embeddings: 256-dim stored in Pinecone (approx kNN)
// - Product embeddings: 256-dim generated by CLIP (image+text)
// - Interaction matrix: ClickHouse (user_id, product_id, score, ts)
// - Model serving: TensorFlow Serving / ONNX Runtime
// ============================================================

import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { HttpService } from '@nestjs/axios';
import { firstValueFrom } from 'rxjs';
import { RedisClientService } from '@hypercommerce/redis';
import { APP_CONSTANTS } from '@hypercommerce/common/constants/app.constants';

export interface RecommendationContext {
  userId: string;
  sessionId: string;
  currentProductId?: string;  // "More like this"
  categoryId?: string;        // Category page context
  limit?: number;
  excludeProductIds?: string[];
  platform: 'IOS' | 'ANDROID' | 'WEB';
  countryCode: string;
}

export interface RecommendedProduct {
  productId: string;
  score: number;
  reason: 'COLLABORATIVE' | 'CONTENT_BASED' | 'TRENDING' | 'SPONSORED';
  rankPosition: number;
}

interface UserEmbedding {
  userId: string;
  vector: number[];
  updatedAt: string;
}

interface ProductEmbedding {
  productId: string;
  vector: number[];
  contentFeatures: {
    category: string;
    brand: string;
    priceRange: 'BUDGET' | 'MID' | 'PREMIUM' | 'LUXURY';
    tags: string[];
  };
}

@Injectable()
export class RecommendationService implements OnModuleInit {
  private readonly logger = new Logger(RecommendationService.name);

  // Embedding cache TTL
  private readonly EMBEDDING_CACHE_TTL = 3600; // 1 hour
  // Recommendation cache TTL (shorter — personalization must stay fresh)
  private readonly REC_CACHE_TTL = 300; // 5 minutes

  // Scoring weights
  private readonly WEIGHTS = {
    collaborative: 0.5,
    content: 0.3,
    recency: 0.1,
    business: 0.1,
  } as const;

  constructor(
    private readonly redis: RedisClientService,
    private readonly http: HttpService,
    private readonly config: ConfigService,
  ) {}

  async onModuleInit(): Promise<void> {
    this.logger.log('RecommendationService initialized');
  }

  /**
   * Get personalized recommendations for a user.
   *
   * Flow:
   * 1. Check cache → return immediately if fresh
   * 2. Fetch user embedding from vector store
   * 3. kNN search → candidate set of 500 products
   * 4. Filter: out-of-stock, blocked, already purchased
   * 5. Score each candidate with business rules overlay
   * 6. Sort, truncate to limit, cache result
   */
  async getPersonalized(ctx: RecommendationContext): Promise<RecommendedProduct[]> {
    const limit = ctx.limit ?? 20;
    const cacheKey = `rec:personal:${ctx.userId}:${ctx.categoryId ?? 'all'}`;

    // ── Cache hit ─────────────────────────────────────────
    const cached = await this.redis.get(cacheKey);
    if (cached) {
      const result = JSON.parse(cached) as RecommendedProduct[];
      return this.excludeProducts(result, ctx.excludeProductIds).slice(0, limit);
    }

    // ── Fetch user embedding ──────────────────────────────
    const userEmbedding = await this.getUserEmbedding(ctx.userId);

    let candidates: RecommendedProduct[];

    if (!userEmbedding) {
      // Cold start — new user with no history
      candidates = await this.getColdStartRecommendations(ctx, limit * 3);
    } else {
      // Warm start — fetch from vector store
      candidates = await this.getCollaborativeRecommendations(
        userEmbedding,
        ctx,
        limit * 3,
      );
    }

    // ── Content-based re-rank ─────────────────────────────
    if (ctx.currentProductId) {
      candidates = await this.blendContentBased(
        ctx.currentProductId,
        candidates,
        this.WEIGHTS.content,
      );
    }

    // ── Business rules overlay ────────────────────────────
    candidates = this.applyBusinessRules(candidates, ctx);

    // ── Diversity injection ───────────────────────────────
    candidates = this.enforceDiversity(candidates);

    // ── Sort and cache ────────────────────────────────────
    candidates.sort((a, b) => b.score - a.score);
    const final = candidates.slice(0, limit * 2); // Cache 2x limit

    await this.redis.set(cacheKey, JSON.stringify(final), this.REC_CACHE_TTL);

    return this.excludeProducts(final, ctx.excludeProductIds).slice(0, limit);
  }

  /**
   * Get "more like this" recommendations.
   * Pure content-based: CLIP embedding similarity.
   */
  async getSimilarProducts(
    productId: string,
    limit = 10,
  ): Promise<RecommendedProduct[]> {
    const cacheKey = `rec:similar:${productId}`;
    const cached = await this.redis.get(cacheKey);
    if (cached) return JSON.parse(cached) as RecommendedProduct[];

    const embedding = await this.getProductEmbedding(productId);
    if (!embedding) return [];

    const similar = await this.vectorSearch(
      embedding.vector,
      'product_embeddings',
      limit,
      { excludeIds: [productId] },
    );

    const result: RecommendedProduct[] = similar.map((item, i) => ({
      productId: item.id,
      score: item.score,
      reason: 'CONTENT_BASED',
      rankPosition: i + 1,
    }));

    await this.redis.set(cacheKey, JSON.stringify(result), 3600);
    return result;
  }

  /**
   * Real-time collaborative filtering via vector kNN.
   *
   * Two-tower model:
   * - User tower: encodes interaction history → 256-dim
   * - Item tower: encodes product features → 256-dim
   * - Dot product → relevance score
   * - Train offline on GPU cluster, serve via Pinecone/Weaviate
   */
  private async getCollaborativeRecommendations(
    userEmbedding: UserEmbedding,
    ctx: RecommendationContext,
    limit: number,
  ): Promise<RecommendedProduct[]> {
    const filter: Record<string, unknown> = {};
    if (ctx.countryCode) {
      filter['available_countries'] = { $in: [ctx.countryCode] };
    }
    if (ctx.categoryId) {
      filter['category_id'] = { $eq: ctx.categoryId };
    }

    const results = await this.vectorSearch(
      userEmbedding.vector,
      'product_embeddings',
      limit,
      filter,
    );

    return results.map((item, i) => ({
      productId: item.id,
      score: item.score * this.WEIGHTS.collaborative,
      reason: 'COLLABORATIVE' as const,
      rankPosition: i + 1,
    }));
  }

  /**
   * Cold-start strategy:
   * 1. Trending products (global)
   * 2. Category bestsellers
   * 3. Editorial picks
   *
   * Personalization kicks in after 3+ interactions (quick warm-up).
   */
  private async getColdStartRecommendations(
    ctx: RecommendationContext,
    limit: number,
  ): Promise<RecommendedProduct[]> {
    // Trending products from Redis sorted set (updated every minute by Analytics)
    const trendingKey = ctx.categoryId
      ? `trending:category:${ctx.categoryId}`
      : 'trending:global';

    const trending = await (this.redis.getClient() as import('ioredis').Redis).zrevrange(
      trendingKey,
      0,
      limit - 1,
      'WITHSCORES',
    );

    const result: RecommendedProduct[] = [];
    for (let i = 0; i < trending.length; i += 2) {
      result.push({
        productId: trending[i],
        score: Number(trending[i + 1]),
        reason: 'TRENDING',
        rankPosition: Math.floor(i / 2) + 1,
      });
    }

    return result;
  }

  /**
   * Blend content-based scores into collaborative results.
   * Given: "viewing product X" → boost items similar to X.
   */
  private async blendContentBased(
    seedProductId: string,
    candidates: RecommendedProduct[],
    weight: number,
  ): Promise<RecommendedProduct[]> {
    const embedding = await this.getProductEmbedding(seedProductId);
    if (!embedding) return candidates;

    const candidateIds = candidates.map((c) => c.productId);
    const similarities = await this.batchCosineSimilarity(
      embedding.vector,
      candidateIds,
    );

    return candidates.map((candidate) => ({
      ...candidate,
      score: candidate.score + (similarities.get(candidate.productId) ?? 0) * weight,
    }));
  }

  /**
   * Business rules applied after ML scoring.
   * - Sponsored products: guaranteed rank slots
   * - Margin boost: high-margin products get +10%
   * - Out-of-stock: penalize to bottom
   * - New seller boost: helps discovery
   */
  private applyBusinessRules(
    candidates: RecommendedProduct[],
    ctx: RecommendationContext,
  ): RecommendedProduct[] {
    return candidates.map((c) => {
      // Placeholder — in production: fetch product flags from cache
      return c;
    });
  }

  /**
   * Diversity enforcement — avoid same brand/category runs.
   * Category-aware interleaving: no more than 3 consecutive same category.
   */
  private enforceDiversity(candidates: RecommendedProduct[]): RecommendedProduct[] {
    // Simplified — in production: fetch category for each candidate
    // and apply interleaving algorithm (Maximal Marginal Relevance)
    return candidates;
  }

  // ── Vector Store Abstraction ──────────────────────────────

  /**
   * kNN search via Pinecone (or Weaviate/Qdrant as alternative).
   * In production: abstracted behind VectorStoreService with
   * failover between providers.
   */
  private async vectorSearch(
    queryVector: number[],
    namespace: string,
    topK: number,
    filter?: Record<string, unknown>,
  ): Promise<Array<{ id: string; score: number }>> {
    try {
      const response = await firstValueFrom(
        this.http.post<{ matches: Array<{ id: string; score: number }> }>(
          `${this.config.get('PINECONE_HOST')}/query`,
          {
            vector: queryVector,
            topK,
            filter,
            includeMetadata: false,
            namespace,
          },
          {
            headers: { 'Api-Key': this.config.get('PINECONE_API_KEY') },
            timeout: 200, // 200ms SLA for recommendation calls
          },
        ),
      );

      return response.data.matches;
    } catch {
      return [];
    }
  }

  private async getUserEmbedding(userId: string): Promise<UserEmbedding | null> {
    const cacheKey = `embedding:user:${userId}`;
    const cached = await this.redis.get(cacheKey);
    if (cached) return JSON.parse(cached) as UserEmbedding;

    // Fetch from Pinecone user namespace
    // In production: user embeddings updated by offline ML pipeline
    return null;
  }

  private async getProductEmbedding(
    productId: string,
  ): Promise<ProductEmbedding | null> {
    const cacheKey = `embedding:product:${productId}`;
    const cached = await this.redis.get(cacheKey);
    if (cached) return JSON.parse(cached) as ProductEmbedding;
    return null;
  }

  /**
   * Cosine similarity between a query vector and multiple stored vectors.
   * Formula: cos(θ) = (A·B) / (|A| × |B|)
   *
   * This is done client-side for small candidate sets (<500).
   * For larger sets → delegate to vector store.
   */
  private async batchCosineSimilarity(
    queryVector: number[],
    productIds: string[],
  ): Promise<Map<string, number>> {
    const result = new Map<string, number>();

    const qNorm = Math.sqrt(queryVector.reduce((sum, v) => sum + v * v, 0));
    if (qNorm === 0) return result;

    for (const productId of productIds) {
      const embedding = await this.getProductEmbedding(productId);
      if (!embedding) continue;

      const dot = embedding.vector.reduce(
        (sum, v, i) => sum + v * (queryVector[i] ?? 0),
        0,
      );
      const pNorm = Math.sqrt(embedding.vector.reduce((s, v) => s + v * v, 0));

      result.set(productId, pNorm === 0 ? 0 : dot / (qNorm * pNorm));
    }

    return result;
  }

  private excludeProducts(
    products: RecommendedProduct[],
    excludeIds?: string[],
  ): RecommendedProduct[] {
    if (!excludeIds?.length) return products;
    const excluded = new Set(excludeIds);
    return products.filter((p) => !excluded.has(p.productId));
  }
}
