// ============================================================
// Mock data — used by Next.js API routes as fallback when
// real microservices are unavailable in development.
// ============================================================

import type { Product, Order, SearchResult } from '@/types';

// ── Products ─────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'iPhone 15 Pro Max 256GB Titan Tự Nhiên',
    slug: 'iphone-15-pro-max-256gb',
    description: 'Điện thoại cao cấp nhất từ Apple với chip A17 Pro, camera 48MP ProRAW.',
    price: 29990000,
    originalPrice: 34990000,
    salePrice: 29990000,
    images: ['https://placehold.co/800x800/f5f5f5/333?text=iPhone+15+Pro'],
    thumbnailUrl: 'https://placehold.co/400x400/f5f5f5/333?text=iPhone+15+Pro',
    sellerId: 'seller-1',
    sellerName: 'Apple Store Chính Hãng',
    categoryId: 'cat-phone',
    categoryName: 'Điện thoại',
    rating: 4.9,
    reviewCount: 2340,
    soldCount: 5820,
    stockQuantity: 48,
    isFlashSale: false,
    isSponsored: false,
    tags: ['apple', 'iphone', 'flagship'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-2',
    name: 'Samsung Galaxy S24 Ultra 256GB',
    slug: 'samsung-galaxy-s24-ultra',
    description: 'Điện thoại flagship Android với S-Pen, camera zoom 100x.',
    price: 26990000,
    originalPrice: 29990000,
    salePrice: 26990000,
    images: ['https://placehold.co/800x800/f0f0f8/333?text=Galaxy+S24+Ultra'],
    thumbnailUrl: 'https://placehold.co/400x400/f0f0f8/333?text=Galaxy+S24+Ultra',
    sellerId: 'seller-2',
    sellerName: 'Samsung Official Store',
    categoryId: 'cat-phone',
    categoryName: 'Điện thoại',
    rating: 4.8,
    reviewCount: 1820,
    soldCount: 4120,
    stockQuantity: 62,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    isSponsored: true,
    adImpressionId: 'imp-s24',
    tags: ['samsung', 'android', 'flagship'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-3',
    name: 'Laptop ASUS ROG Zephyrus G14 RTX 4060',
    slug: 'asus-rog-zephyrus-g14',
    description: 'Laptop gaming siêu mỏng nhẹ, AMD Ryzen 9, RTX 4060, màn hình 144Hz.',
    price: 42000000,
    originalPrice: 48000000,
    salePrice: 42000000,
    images: ['https://placehold.co/800x800/1a1a2e/eee?text=ROG+Laptop'],
    thumbnailUrl: 'https://placehold.co/400x400/1a1a2e/eee?text=ROG+Laptop',
    sellerId: 'seller-3',
    sellerName: 'ASUS Authorized Store',
    categoryId: 'cat-laptop',
    categoryName: 'Laptop',
    rating: 4.7,
    reviewCount: 890,
    soldCount: 1240,
    stockQuantity: 15,
    isFlashSale: false,
    isSponsored: false,
    tags: ['asus', 'rog', 'gaming', 'laptop'],
    shippingInfo: { estimatedDays: 2, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-4',
    name: 'Tai nghe Sony WH-1000XM5 Chống Ồn',
    slug: 'sony-wh-1000xm5',
    description: 'Tai nghe over-ear premium với ANC tốt nhất, pin 30 giờ, kết nối đa điểm.',
    price: 7490000,
    originalPrice: 8990000,
    salePrice: 7490000,
    images: ['https://placehold.co/800x800/222/eee?text=Sony+WH-1000XM5'],
    thumbnailUrl: 'https://placehold.co/400x400/222/eee?text=Sony+WH-1000XM5',
    sellerId: 'seller-4',
    sellerName: 'Sony Store VN',
    categoryId: 'cat-audio',
    categoryName: 'Âm thanh',
    rating: 4.9,
    reviewCount: 3120,
    soldCount: 7840,
    stockQuantity: 89,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    isSponsored: false,
    tags: ['sony', 'headphones', 'anc'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-5',
    name: 'Apple Watch Series 9 GPS 41mm',
    slug: 'apple-watch-series-9-41mm',
    description: 'Đồng hồ thông minh với chip S9, màn hình Retina sáng 2000 nit.',
    price: 11990000,
    originalPrice: 13990000,
    salePrice: 11990000,
    images: ['https://placehold.co/800x800/e8f4fd/333?text=Apple+Watch+S9'],
    thumbnailUrl: 'https://placehold.co/400x400/e8f4fd/333?text=Apple+Watch+S9',
    sellerId: 'seller-1',
    sellerName: 'Apple Store Chính Hãng',
    categoryId: 'cat-wearable',
    categoryName: 'Đồng hồ thông minh',
    rating: 4.8,
    reviewCount: 1450,
    soldCount: 3280,
    stockQuantity: 35,
    isFlashSale: false,
    isSponsored: false,
    tags: ['apple', 'smartwatch', 'wearable'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-6',
    name: 'iPad Pro M2 11 inch Wi-Fi 128GB',
    slug: 'ipad-pro-m2-11-128gb',
    description: 'Máy tính bảng mạnh mẽ với chip M2, màn hình ProMotion 120Hz.',
    price: 21990000,
    originalPrice: 24990000,
    salePrice: 21990000,
    images: ['https://placehold.co/800x800/f8f8f8/333?text=iPad+Pro+M2'],
    thumbnailUrl: 'https://placehold.co/400x400/f8f8f8/333?text=iPad+Pro+M2',
    sellerId: 'seller-1',
    sellerName: 'Apple Store Chính Hãng',
    categoryId: 'cat-tablet',
    categoryName: 'Máy tính bảng',
    rating: 4.7,
    reviewCount: 980,
    soldCount: 2140,
    stockQuantity: 28,
    isFlashSale: false,
    isSponsored: true,
    adImpressionId: 'imp-ipad',
    tags: ['apple', 'ipad', 'tablet'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-7',
    name: 'Nike Air Max 270 Nam Đen Trắng',
    slug: 'nike-air-max-270-nam',
    description: 'Giày sneaker thể thao đệm Air Max lớn, phong cách streetwear.',
    price: 3200000,
    originalPrice: 4200000,
    salePrice: 3200000,
    images: ['https://placehold.co/800x800/fff/333?text=Nike+Air+Max'],
    thumbnailUrl: 'https://placehold.co/400x400/fff/333?text=Nike+Air+Max',
    sellerId: 'seller-5',
    sellerName: 'Nike Vietnam Official',
    categoryId: 'cat-shoes',
    categoryName: 'Giày dép',
    rating: 4.6,
    reviewCount: 2890,
    soldCount: 9120,
    stockQuantity: 156,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    isSponsored: false,
    tags: ['nike', 'sneaker', 'airmax'],
    shippingInfo: { estimatedDays: 2, freeShipping: false, fee: 30000 },
  },
  {
    id: 'prod-8',
    name: 'Áo Thun Uniqlo AIRism Cổ Tròn Nam',
    slug: 'ao-thun-uniqlo-airism',
    description: 'Áo thun vải thoáng mát, co giãn 4 chiều, kháng khuẩn khử mùi.',
    price: 499000,
    originalPrice: 699000,
    salePrice: 499000,
    images: ['https://placehold.co/800x800/e8f5e9/333?text=Uniqlo+Tshirt'],
    thumbnailUrl: 'https://placehold.co/400x400/e8f5e9/333?text=Uniqlo+Tshirt',
    sellerId: 'seller-6',
    sellerName: 'Uniqlo Vietnam',
    categoryId: 'cat-fashion',
    categoryName: 'Thời trang',
    rating: 4.5,
    reviewCount: 5420,
    soldCount: 28400,
    stockQuantity: 500,
    isFlashSale: false,
    isSponsored: false,
    tags: ['uniqlo', 'fashion', 'tshirt'],
    shippingInfo: { estimatedDays: 2, freeShipping: false, fee: 30000 },
  },
  {
    id: 'prod-9',
    name: 'Son MAC Ruby Woo Màu Đỏ Classic',
    slug: 'son-mac-ruby-woo',
    description: 'Son môi màu đỏ biểu tượng của MAC, lâu trôi, texture matte.',
    price: 850000,
    originalPrice: 950000,
    salePrice: 850000,
    images: ['https://placehold.co/800x800/fce4ec/333?text=MAC+Ruby+Woo'],
    thumbnailUrl: 'https://placehold.co/400x400/fce4ec/333?text=MAC+Ruby+Woo',
    sellerId: 'seller-7',
    sellerName: 'MAC Cosmetics Official',
    categoryId: 'cat-beauty',
    categoryName: 'Làm đẹp',
    rating: 4.8,
    reviewCount: 8920,
    soldCount: 45000,
    stockQuantity: 320,
    isFlashSale: false,
    isSponsored: false,
    tags: ['mac', 'lipstick', 'beauty'],
    shippingInfo: { estimatedDays: 2, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-10',
    name: 'Bàn phím cơ Keychron K2 Pro RGB',
    slug: 'keychron-k2-pro-rgb',
    description: 'Bàn phím cơ compact 75%, kết nối Bluetooth 5.1 + USB-C, switch Gateron.',
    price: 2100000,
    originalPrice: 2500000,
    salePrice: 2100000,
    images: ['https://placehold.co/800x800/fafafa/333?text=Keychron+K2+Pro'],
    thumbnailUrl: 'https://placehold.co/400x400/fafafa/333?text=Keychron+K2+Pro',
    sellerId: 'seller-8',
    sellerName: 'Keychron Vietnam',
    categoryId: 'cat-accessories',
    categoryName: 'Phụ kiện máy tính',
    rating: 4.7,
    reviewCount: 1240,
    soldCount: 3600,
    stockQuantity: 72,
    isFlashSale: false,
    isSponsored: false,
    tags: ['keychron', 'keyboard', 'mechanical'],
    shippingInfo: { estimatedDays: 2, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-11',
    name: 'Chuột Logitech MX Master 3S Silent',
    slug: 'logitech-mx-master-3s',
    description: 'Chuột không dây cao cấp, MagSpeed scroll, thiết kế ergonomic.',
    price: 1890000,
    originalPrice: 2290000,
    salePrice: 1890000,
    images: ['https://placehold.co/800x800/f5f0ff/333?text=MX+Master+3S'],
    thumbnailUrl: 'https://placehold.co/400x400/f5f0ff/333?text=MX+Master+3S',
    sellerId: 'seller-8',
    sellerName: 'Keychron Vietnam',
    categoryId: 'cat-accessories',
    categoryName: 'Phụ kiện máy tính',
    rating: 4.8,
    reviewCount: 2140,
    soldCount: 6820,
    stockQuantity: 94,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    isSponsored: false,
    tags: ['logitech', 'mouse', 'wireless'],
    shippingInfo: { estimatedDays: 1, freeShipping: true, fee: 0 },
  },
  {
    id: 'prod-12',
    name: 'Sách Đắc Nhân Tâm - Dale Carnegie',
    slug: 'sach-dac-nhan-tam',
    description: 'Cuốn sách self-help bán chạy nhất mọi thời đại, bản dịch mới nhất 2024.',
    price: 95000,
    originalPrice: 120000,
    salePrice: 95000,
    images: ['https://placehold.co/800x800/fff8e1/333?text=Đắc+Nhân+Tâm'],
    thumbnailUrl: 'https://placehold.co/400x400/fff8e1/333?text=Đắc+Nhân+Tâm',
    sellerId: 'seller-9',
    sellerName: 'Nhà Xuất Bản Trẻ',
    categoryId: 'cat-books',
    categoryName: 'Sách',
    rating: 4.9,
    reviewCount: 12400,
    soldCount: 89000,
    stockQuantity: 1200,
    isFlashSale: false,
    isSponsored: false,
    tags: ['sach', 'self-help', 'carnegie'],
    shippingInfo: { estimatedDays: 3, freeShipping: false, fee: 20000 },
  },
];

export const MOCK_FEATURED_PRODUCTS = MOCK_PRODUCTS;
export const MOCK_FLASH_SALE_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.isFlashSale);

export const MOCK_SEARCH_RESULT: SearchResult = {
  products: MOCK_PRODUCTS,
  total: MOCK_PRODUCTS.length,
  page: 1,
  pageSize: 24,
  sponsored: MOCK_PRODUCTS.filter((p) => p.isSponsored),
};

// ── Orders ───────────────────────────────────────────────────

export const MOCK_ORDERS = [
  {
    id: 'ord-001',
    status: 'DELIVERED',
    totalAmount: 37480000,
    subtotal: 37480000,
    shippingFee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    trackingNumber: 'VNP-001234567',
    estimatedDelivery: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    paymentMethod: 'VNPAY',
    sellerName: 'Apple Store Chính Hãng',
    shippingAddress: {
      fullName: 'Nguyễn Văn A',
      phone: '0912345678',
      province: 'Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      street: '123 Nguyễn Huệ',
    },
    items: [
      {
        id: 'oi-001-1',
        productId: 'prod-1',
        productName: 'iPhone 15 Pro Max 256GB Titan Tự Nhiên',
        imageUrl: 'https://placehold.co/400x400/f5f5f5/333?text=iPhone+15+Pro',
        quantity: 1,
        price: 29990000,
        total: 29990000,
      },
      {
        id: 'oi-001-2',
        productId: 'prod-5',
        productName: 'Apple Watch Series 9 GPS 41mm',
        imageUrl: 'https://placehold.co/400x400/e8f4fd/333?text=Apple+Watch+S9',
        quantity: 1,
        price: 11990000,
        total: 11990000,
      },
    ],
  },
  {
    id: 'ord-002',
    status: 'SHIPPED',
    totalAmount: 8490000,
    subtotal: 8490000,
    shippingFee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    trackingNumber: 'VNP-001234568',
    estimatedDelivery: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(),
    paymentMethod: 'COD',
    sellerName: 'Sony Store VN',
    shippingAddress: {
      fullName: 'Nguyễn Văn A',
      phone: '0912345678',
      province: 'Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      street: '123 Nguyễn Huệ',
    },
    items: [
      {
        id: 'oi-002-1',
        productId: 'prod-4',
        productName: 'Tai nghe Sony WH-1000XM5 Chống Ồn',
        imageUrl: 'https://placehold.co/400x400/222/eee?text=Sony+WH-1000XM5',
        quantity: 1,
        price: 7490000,
        total: 7490000,
      },
    ],
  },
  {
    id: 'ord-003',
    status: 'PROCESSING',
    totalAmount: 3730000,
    subtotal: 3730000,
    shippingFee: 30000,
    discount: 0,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    trackingNumber: null,
    estimatedDelivery: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
    paymentMethod: 'MOMO',
    sellerName: 'Nike Vietnam Official',
    shippingAddress: {
      fullName: 'Nguyễn Văn A',
      phone: '0912345678',
      province: 'Hà Nội',
      district: 'Hoàn Kiếm',
      ward: 'Phường Hàng Trống',
      street: '45 Đinh Tiên Hoàng',
    },
    items: [
      {
        id: 'oi-003-1',
        productId: 'prod-7',
        productName: 'Nike Air Max 270 Nam Đen Trắng',
        imageUrl: 'https://placehold.co/400x400/fff/333?text=Nike+Air+Max',
        quantity: 1,
        price: 3200000,
        total: 3200000,
      },
    ],
  },
  {
    id: 'ord-004',
    status: 'PENDING',
    totalAmount: 2195000,
    subtotal: 2195000,
    shippingFee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    trackingNumber: null,
    estimatedDelivery: null,
    paymentMethod: 'VNPAY',
    sellerName: 'Keychron Vietnam',
    shippingAddress: {
      fullName: 'Nguyễn Văn A',
      phone: '0912345678',
      province: 'Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      street: '123 Nguyễn Huệ',
    },
    items: [
      {
        id: 'oi-004-1',
        productId: 'prod-10',
        productName: 'Bàn phím cơ Keychron K2 Pro RGB',
        imageUrl: 'https://placehold.co/400x400/fafafa/333?text=Keychron+K2+Pro',
        quantity: 1,
        price: 2100000,
        total: 2100000,
      },
    ],
  },
  {
    id: 'ord-005',
    status: 'CANCELLED',
    totalAmount: 499000,
    subtotal: 499000,
    shippingFee: 0,
    discount: 0,
    createdAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 13 * 24 * 3600 * 1000).toISOString(),
    trackingNumber: null,
    estimatedDelivery: null,
    paymentMethod: 'MOMO',
    sellerName: 'Uniqlo Vietnam',
    shippingAddress: {
      fullName: 'Nguyễn Văn A',
      phone: '0912345678',
      province: 'Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      street: '123 Nguyễn Huệ',
    },
    items: [
      {
        id: 'oi-005-1',
        productId: 'prod-8',
        productName: 'Áo Thun Uniqlo AIRism Cổ Tròn Nam',
        imageUrl: 'https://placehold.co/400x400/e8f5e9/333?text=Uniqlo+Tshirt',
        quantity: 1,
        price: 499000,
        total: 499000,
      },
    ],
  },
];

// ── Notifications ─────────────────────────────────────────────

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'ORDER_CONFIRMED',
    title: 'Đơn hàng đã được xác nhận',
    body: 'Đơn hàng #ORD-001 của bạn đã được xác nhận và đang được chuẩn bị.',
    readAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    metadata: { orderId: 'ord-001' },
  },
  {
    id: 'notif-2',
    type: 'ORDER_SHIPPED',
    title: 'Đơn hàng đang được giao',
    body: 'Đơn hàng #ORD-002 đang trên đường giao tới bạn. Mã vận đơn: VNP-001234568.',
    readAt: null,
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    metadata: { orderId: 'ord-002', trackingNumber: 'VNP-001234568' },
  },
  {
    id: 'notif-3',
    type: 'FLASH_SALE',
    title: '⚡ Flash Sale bắt đầu lúc 12:00!',
    body: 'Giảm đến 50% điện thoại, tai nghe, laptop. Số lượng có hạn!',
    readAt: null,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    metadata: {},
  },
  {
    id: 'notif-4',
    type: 'PAYMENT_SUCCESS',
    title: 'Thanh toán thành công',
    body: 'Thanh toán 3.730.000₫ cho đơn hàng #ORD-003 đã được xử lý thành công.',
    readAt: null,
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    metadata: { orderId: 'ord-003', amount: '3730000' },
  },
  {
    id: 'notif-5',
    type: 'PROMOTION',
    title: '🏷️ Voucher độc quyền cho bạn',
    body: 'Nhập HYPER20 để giảm thêm 20% cho đơn hàng tiếp theo. Hết hạn 31/12.',
    readAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    metadata: { code: 'HYPER20' },
  },
  {
    id: 'notif-6',
    type: 'ORDER_DELIVERED',
    title: 'Đơn hàng đã giao thành công',
    body: 'Đơn hàng #ORD-001 đã được giao thành công. Hãy đánh giá sản phẩm nhé!',
    readAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    metadata: { orderId: 'ord-001' },
  },
  {
    id: 'notif-7',
    type: 'SYSTEM',
    title: '🔔 Chào mừng đến với HyperCommerce!',
    body: 'Tài khoản của bạn đã được tạo thành công. Khám phá hàng triệu sản phẩm ngay!',
    readAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    metadata: {},
  },
  {
    id: 'notif-8',
    type: 'FLASH_SALE',
    title: '⚡ Còn 30 phút! Flash Sale sắp kết thúc',
    body: 'Đừng bỏ lỡ Sony WH-1000XM5 giảm 20%, iPhone 15 Pro giảm 15%.',
    readAt: null,
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    metadata: {},
  },
];

// ── Demo Users ────────────────────────────────────────────────

export const DEMO_USERS = [
  {
    id: 'user-admin-1',
    email: 'admin@hypercommerce.vn',
    password: 'password',
    fullName: 'Admin HyperCommerce',
    avatar: 'https://placehold.co/100x100/EE4D2D/fff?text=A',
    role: 'ADMIN',
    sellerId: undefined as string | undefined,
    points: 5000,
  },
  {
    id: 'user-buyer-1',
    email: 'user@hypercommerce.vn',
    password: 'password',
    fullName: 'Nguyễn Văn A',
    avatar: 'https://placehold.co/100x100/4CAF50/fff?text=A',
    role: 'BUYER',
    sellerId: undefined as string | undefined,
    points: 1240,
  },
  {
    id: 'user-seller-1',
    email: 'seller@hypercommerce.vn',
    password: 'password',
    fullName: 'Trần Thị B (Seller)',
    avatar: 'https://placehold.co/100x100/2196F3/fff?text=B',
    role: 'SELLER',
    sellerId: 'seller-demo-1',
    points: 890,
  },
];

// ── Points & Referral ────────────────────────────────────────

export const MOCK_POINT_TRANSACTIONS = [
  {
    id: 'pt-1',
    type: 'EARN',
    amount: 300,
    description: 'Mua hàng đơn #ORD-001',
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pt-2',
    type: 'EARN',
    amount: 85,
    description: 'Mua hàng đơn #ORD-002',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pt-3',
    type: 'EARN',
    amount: 200,
    description: 'Mã giới thiệu thành công',
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pt-4',
    type: 'REDEEM',
    amount: -500,
    description: 'Đổi voucher giảm 50.000₫',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'pt-5',
    type: 'EARN',
    amount: 50,
    description: 'Đánh giá sản phẩm',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_POINT_REWARDS = [
  {
    id: 'reward-1',
    name: 'Voucher giảm 50.000₫',
    pointsCost: 500,
    value: 50000,
    stock: 100,
    imageUrl: 'https://placehold.co/200x200/EE4D2D/fff?text=50K',
  },
  {
    id: 'reward-2',
    name: 'Voucher giảm 100.000₫',
    pointsCost: 900,
    value: 100000,
    stock: 50,
    imageUrl: 'https://placehold.co/200x200/EE4D2D/fff?text=100K',
  },
  {
    id: 'reward-3',
    name: 'Freeship toàn quốc',
    pointsCost: 200,
    value: 30000,
    stock: 200,
    imageUrl: 'https://placehold.co/200x200/4CAF50/fff?text=FREE+SHIP',
  },
  {
    id: 'reward-4',
    name: 'Voucher giảm 200.000₫',
    pointsCost: 1800,
    value: 200000,
    stock: 20,
    imageUrl: 'https://placehold.co/200x200/EE4D2D/fff?text=200K',
  },
];

// ── Admin mock data ────────────────────────────────────────────

export const MOCK_ADMIN_STATS = {
  revenue: { today: 842000000, week: 5840000000, month: 24800000000, growth: 18.4 },
  orders: { today: 1240, week: 8940, month: 38200, growth: 12.1 },
  users: { total: 284000, newToday: 342, growth: 8.2 },
  sellers: { total: 12400, verified: 10200, pending: 320 },
  avgOrderValue: 672000,
  cancelRate: 2.8,
  revenueChart: Array.from({ length: 7 }, (_, i) => ({
    date: new Date(Date.now() - (6 - i) * 24 * 3600 * 1000).toLocaleDateString('vi-VN', {
      month: 'short',
      day: 'numeric',
    }),
    commissions: Math.round(50000000 + Math.random() * 30000000),
    adRevenue: Math.round(20000000 + Math.random() * 10000000),
    subscriptions: Math.round(5000000 + Math.random() * 3000000),
  })),
  serviceHealth: [
    { name: 'user-service', status: 'healthy', latency: 12, port: 3005 },
    { name: 'order-service', status: 'healthy', latency: 18, port: 3011 },
    { name: 'payment-service', status: 'healthy', latency: 24, port: 3003 },
    { name: 'inventory-service', status: 'healthy', latency: 15, port: 3002 },
    { name: 'notification-service', status: 'healthy', latency: 9, port: 3004 },
    { name: 'search-service', status: 'healthy', latency: 35, port: 3010 },
    { name: 'ai-service', status: 'healthy', latency: 280, port: 3006 },
    { name: 'live-service', status: 'healthy', latency: 8, port: 3007 },
    { name: 'feed-service', status: 'healthy', latency: 22, port: 3008 },
    { name: 'analytics-service', status: 'healthy', latency: 45, port: 3009 },
  ],
};

export const MOCK_ADMIN_USERS = Array.from({ length: 20 }, (_, i) => ({
  id: `admin-user-${i + 1}`,
  email: `user${i + 1}@example.com`,
  fullName: `Người dùng ${i + 1}`,
  role: i === 0 ? 'ADMIN' : i < 5 ? 'SELLER' : 'BUYER',
  status: i === 3 ? 'BANNED' : 'ACTIVE',
  createdAt: new Date(Date.now() - (i + 1) * 3 * 24 * 3600 * 1000).toISOString(),
  totalOrders: Math.floor(Math.random() * 50),
  totalSpent: Math.floor(Math.random() * 50000000),
}));

export const MOCK_ADMIN_ORDERS = Array.from({ length: 20 }, (_, i) => {
  const amt = Math.round((500000 + ((i * 1234567) % 30000000)) / 1000) * 1000;
  const ts = new Date(Date.now() - i * 6 * 3600 * 1000).toISOString();
  return {
    id: `ord-admin-${String(i + 1).padStart(3, '0')}`,
    user_id: `user-${(i % 10) + 1}`,
    seller_id: `seller-${(i % 3) + 1}`,
    buyerEmail: `user${(i % 10) + 1}@example.com`,
    buyerName: `Người dùng ${(i % 10) + 1}`,
    sellerName: ['Apple Store', 'Samsung Official', 'Nike Vietnam'][i % 3],
    status: ['PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'][i % 5],
    total_amount: amt,
    itemCount: (i % 5) + 1,
    paymentMethod: ['COD', 'VNPAY', 'MOMO', 'STRIPE'][i % 4],
    created_at: ts,
  };
});

export const MOCK_ADMIN_SELLERS = Array.from({ length: 10 }, (_, i) => ({
  id: `seller-${i + 1}`,
  shopName: [
    'Apple Store VN',
    'Samsung Official',
    'Nike Vietnam',
    'Sony Store',
    'Uniqlo VN',
    'ASUS Store',
    'MAC Cosmetics',
    'Keychron VN',
    'NXB Trẻ',
    'Logitech Store',
  ][i],
  email: `seller${i + 1}@example.com`,
  status: i === 4 ? 'SUSPENDED' : i < 8 ? 'VERIFIED' : 'PENDING',
  totalRevenue: Math.round((10000000 + Math.random() * 500000000) / 1000) * 1000,
  totalOrders: Math.floor(100 + Math.random() * 5000),
  rating: (3.5 + Math.random() * 1.5).toFixed(1),
  createdAt: new Date(Date.now() - (i + 1) * 30 * 24 * 3600 * 1000).toISOString(),
}));

export const MOCK_FRAUD_SIGNALS = [
  {
    id: 'fraud-1',
    type: 'SUSPICIOUS_IP',
    risk_level: 'HIGH',
    user_id: 'user-42',
    email: 'user42@example.com',
    signals: ['Multiple accounts from same IP', '3 signups in 1 hour', 'VPN detected'],
    amount: 15000000,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'fraud-2',
    type: 'CHARGEBACK',
    risk_level: 'CRITICAL',
    user_id: 'user-88',
    email: 'user88@example.com',
    signals: ['Chargeback rate > 3%', '5 disputes in 24h', 'Pattern: high-value items'],
    amount: 8500000,
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'fraud-3',
    type: 'VELOCITY',
    risk_level: 'MEDIUM',
    user_id: 'user-15',
    email: 'user15@example.com',
    signals: ['12 orders in 10 minutes', 'Velocity anomaly'],
    amount: 6200000,
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    resolved: false,
  },
  {
    id: 'fraud-4',
    type: 'CARD_TESTING',
    risk_level: 'HIGH',
    user_id: 'user-201',
    email: 'user201@example.com',
    signals: ['Multiple failed card attempts', 'Successful transaction after 8 fails'],
    amount: 299000,
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    resolved: true,
  },
  {
    id: 'fraud-5',
    type: 'ACCOUNT_TAKEOVER',
    risk_level: 'CRITICAL',
    user_id: 'user-330',
    email: 'user330@example.com',
    signals: [
      'Login from new country',
      'Device fingerprint changed',
      'Large order placed immediately',
    ],
    amount: 45000000,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    resolved: false,
  },
];

export const MOCK_CHARGEBACK_RATE = Array.from({ length: 12 }, (_, i) => ({
  week: `T${Math.floor(i / 4) + 1}W${(i % 4) + 1}`,
  chargeback_rate: +(0.5 + Math.random() * 2.5).toFixed(2),
}));

export const MOCK_AD_CAMPAIGNS = [
  {
    id: 'camp-1',
    name: 'Tháng 6 - Flash Sale Weekend',
    seller_id: 'seller-1',
    business_name: 'Apple Store VN',
    type: 'CPC',
    status: 'ACTIVE',
    daily_budget: 10000000,
    spent_today: 6480000,
    budget: 50000000,
    spent: 32400000,
    impressions: 1240000,
    clicks: 48200,
    conversions: 1840,
    ctr: 3.89,
    roas: 12.4,
    startsAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'camp-2',
    name: 'Điện tử - Hè Rực Rỡ',
    seller_id: 'seller-2',
    business_name: 'Samsung Official',
    type: 'CPM',
    status: 'ACTIVE',
    daily_budget: 16000000,
    spent_today: 12240000,
    budget: 80000000,
    spent: 61200000,
    impressions: 2840000,
    clicks: 98400,
    conversions: 3240,
    ctr: 3.46,
    roas: 9.8,
    startsAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 20 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'camp-3',
    name: 'Thời trang - Xu hướng mới',
    seller_id: 'seller-3',
    business_name: 'Nike Vietnam',
    type: 'CPC',
    status: 'PAUSED',
    daily_budget: 6000000,
    spent_today: 0,
    budget: 30000000,
    spent: 18900000,
    impressions: 890000,
    clicks: 24100,
    conversions: 820,
    ctr: 2.71,
    roas: 7.2,
    startsAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 25 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_DISPUTES = [
  {
    id: 'disp-1',
    orderId: 'ord-001',
    buyerName: 'Nguyễn Văn A',
    sellerName: 'Apple Store VN',
    reason: 'Sản phẩm không đúng mô tả',
    status: 'OPEN',
    amount: 29990000,
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    evidence: 'Hình ảnh sản phẩm nhận được',
  },
  {
    id: 'disp-2',
    orderId: 'ord-admin-05',
    buyerName: 'Trần Thị B',
    sellerName: 'Samsung Official',
    reason: 'Hàng bị hỏng khi giao',
    status: 'IN_REVIEW',
    amount: 26990000,
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    evidence: 'Video mở hộp',
  },
  {
    id: 'disp-3',
    orderId: 'ord-admin-12',
    buyerName: 'Lê Văn C',
    sellerName: 'Nike Vietnam',
    reason: 'Chưa nhận được hàng sau 10 ngày',
    status: 'OPEN',
    amount: 3200000,
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    evidence: null,
  },
];

export const MOCK_FEATURE_FLAGS = [
  {
    key: 'FLASH_SALE_V2',
    name: 'Flash Sale V2 UI',
    enabled: true,
    rollout: 100,
    description: 'New flash sale countdown UI',
    updatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'AI_RECOMMENDATIONS',
    name: 'AI Product Recs',
    enabled: true,
    rollout: 80,
    description: 'ML-powered product recommendations',
    updatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'LIVE_SHOPPING_BETA',
    name: 'Live Shopping Beta',
    enabled: false,
    rollout: 0,
    description: 'Beta live shopping features',
    updatedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'REFERRAL_BONUS_2X',
    name: 'Referral 2x Bonus',
    enabled: true,
    rollout: 50,
    description: 'Double referral points campaign',
    updatedAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'NEW_CHECKOUT_FLOW',
    name: 'New Checkout UI',
    enabled: false,
    rollout: 0,
    description: 'Redesigned checkout with saved cards',
    updatedAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'PUSH_NOTIFICATIONS',
    name: 'Web Push Notifs',
    enabled: true,
    rollout: 100,
    description: 'Browser push notifications',
    updatedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'SELLER_ANALYTICS_V2',
    name: 'Seller Analytics V2',
    enabled: true,
    rollout: 100,
    description: 'Enhanced seller dashboard analytics',
    updatedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    key: 'CRYPTO_PAYMENT',
    name: 'Crypto Payments',
    enabled: false,
    rollout: 0,
    description: 'Accept USDT payments (experimental)',
    updatedAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_ROLES = [
  {
    id: 'role-buyer',
    name: 'BUYER',
    role: 'BUYER',
    displayName: 'Người mua',
    description: 'Standard buyer — read catalog, create orders, manage cart & reviews',
    userCount: 271000,
    permissions: ['catalog:read', 'order:create', 'order:read', 'cart:write', 'review:write'],
  },
  {
    id: 'role-seller',
    name: 'SELLER',
    role: 'SELLER',
    displayName: 'Người bán',
    description: 'Verified seller — manage products, orders, analytics & payouts',
    userCount: 10200,
    permissions: [
      'catalog:write',
      'order:manage',
      'inventory:write',
      'analytics:read',
      'payout:request',
      'dispute:respond',
    ],
  },
  {
    id: 'role-admin',
    name: 'ADMIN',
    role: 'ADMIN',
    displayName: 'Quản trị viên',
    description: 'Full system access — manage users, sellers, orders and platform settings',
    userCount: 8,
    permissions: [
      'user:manage',
      'seller:manage',
      'order:manage',
      'dispute:resolve',
      'feature-flag:write',
      'finance:read',
      'audit:read',
      'role:assign',
    ],
  },
  {
    id: 'role-moderator',
    name: 'MODERATOR',
    role: 'MODERATOR',
    displayName: 'Kiểm duyệt viên',
    description: 'Content moderation — review products, moderate reviews & handle disputes',
    userCount: 24,
    permissions: ['product:review', 'review:moderate', 'user:warn', 'dispute:review'],
  },
];

export const MOCK_AUDIT_LOGS = Array.from({ length: 20 }, (_, i) => ({
  id: `log-${i + 1}`,
  actor_id: `admin-${(i % 3) + 1}`,
  actor_email: ['admin@hypercommerce.vn', 'ops@hypercommerce.vn', 'finance@hypercommerce.vn'][
    i % 3
  ],
  actor_role: ['SUPER_ADMIN', 'OPS', 'FINANCE'][i % 3],
  action: [
    'USER_BANNED',
    'SELLER_VERIFIED',
    'ORDER_FORCE_STATUS',
    'FLAG_TOGGLED',
    'ROLE_CHANGED',
    'DISPUTE_RESOLVED',
  ][i % 6],
  resource: ['User', 'Seller', 'Order', 'FeatureFlag', 'User', 'Dispute'][i % 6],
  resource_id: `entity-${i + 1}`,
  success: i % 7 !== 0,
  ip_address: `192.168.1.${(i % 10) + 1}`,
  created_at: new Date(Date.now() - i * 4 * 3600 * 1000).toISOString(),
  changes:
    i % 3 === 0
      ? {
          before: 'ACTIVE',
          after: ['BANNED', 'VERIFIED', 'RESOLVED', 'ON', 'ADMIN', 'CLOSED'][i % 6],
        }
      : undefined,
}));

export const MOCK_FINANCE_REVENUE = {
  weekly: Array.from({ length: 7 }, (_, i) => ({
    date: new Date(Date.now() - (6 - i) * 24 * 3600 * 1000).toLocaleDateString('vi-VN', {
      weekday: 'short',
      day: 'numeric',
    }),
    revenue: Math.round((500000000 + Math.random() * 300000000) / 1000) * 1000,
    orders: Math.floor(800 + Math.random() * 600),
  })),
  pieData: [
    { name: 'Hoa hồng', value: 320000000 },
    { name: 'Quảng cáo', value: 124000000 },
    { name: 'Subscription', value: 48000000 },
    { name: 'Phí cổng TT', value: 28000000 },
  ],
  totalRevenue: 520000000,
  growth: 18.4,
};

export const MOCK_FINANCE_PAYOUTS = Array.from({ length: 10 }, (_, i) => ({
  id: `payout-${i + 1}`,
  sellerName: MOCK_ADMIN_SELLERS[i % MOCK_ADMIN_SELLERS.length].shopName,
  sellerId: `seller-${(i % 10) + 1}`,
  amount: Math.round((5000000 + Math.random() * 50000000) / 1000) * 1000,
  status: i < 3 ? 'PENDING' : i < 7 ? 'PROCESSING' : 'COMPLETED',
  requestedAt: new Date(Date.now() - (i + 1) * 24 * 3600 * 1000).toISOString(),
  bankAccount: `**** ${1000 + i}`,
}));

// ── Seller mock data ──────────────────────────────────────────

export const MOCK_SELLER_ANALYTICS = {
  revenue: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 3600 * 1000).toLocaleDateString('vi-VN', {
      month: 'short',
      day: 'numeric',
    }),
    revenue: Math.round((50000000 + Math.random() * 80000000) / 1000) * 1000,
    orders: Math.floor(80 + Math.random() * 120),
  })),
  topProducts: [
    {
      productId: 'prod-1',
      name: 'iPhone 15 Pro Max',
      views: 48200,
      orders: 1840,
      revenue: 55176000000,
      convRate: 3.82,
    },
    {
      productId: 'prod-2',
      name: 'Samsung Galaxy S24 Ultra',
      views: 32100,
      orders: 1240,
      revenue: 33468000000,
      convRate: 3.86,
    },
    {
      productId: 'prod-5',
      name: 'Apple Watch Series 9',
      views: 28400,
      orders: 980,
      revenue: 11750200000,
      convRate: 3.45,
    },
    {
      productId: 'prod-6',
      name: 'iPad Pro M2',
      views: 18900,
      orders: 640,
      revenue: 14073600000,
      convRate: 3.39,
    },
    {
      productId: 'prod-10',
      name: 'Keychron K2 Pro',
      views: 12400,
      orders: 520,
      revenue: 1092000000,
      convRate: 4.19,
    },
  ],
  funnel: [
    { step: 'Xem sản phẩm', users: 48200 },
    { step: 'Thêm vào giỏ', users: 12840 },
    { step: 'Bắt đầu checkout', users: 6420 },
    { step: 'Đặt hàng thành công', users: 4120 },
  ],
  summary: {
    totalRevenue: 1284000000,
    revenueGrowth: 18.4,
    totalOrders: 4120,
    ordersGrowth: 12.1,
    avgOrderValue: 311650,
    conversionRate: 3.82,
    cancelRate: 2.1,
    returnRate: 1.4,
  },
};

export const MOCK_SELLER_INVENTORY = Array.from({ length: 12 }, (_, i) => ({
  productId: `prod-${i + 1}`,
  productName: [
    'iPhone 15 Pro Max',
    'Samsung Galaxy S24',
    'ASUS ROG Zephyrus',
    'Sony WH-1000XM5',
    'Apple Watch S9',
    'iPad Pro M2',
    'Nike Air Max',
    'Uniqlo AIRism',
    'MAC Ruby Woo',
    'Keychron K2 Pro',
    'Logitech MX Master',
    'Đắc Nhân Tâm',
  ][i],
  sku: `SKU-${String(i + 1).padStart(4, '0')}`,
  stock: [48, 62, 15, 89, 35, 28, 156, 500, 320, 72, 94, 1200][i],
  reserved: [12, 8, 5, 24, 10, 7, 45, 80, 60, 18, 30, 200][i],
  available: [36, 54, 10, 65, 25, 21, 111, 420, 260, 54, 64, 1000][i],
  threshold: [20, 20, 10, 30, 15, 10, 50, 100, 80, 20, 30, 300][i],
  isLowStock: [false, false, true, false, false, false, false, false, false, false, false, false][
    i
  ],
  lastRestocked: new Date(Date.now() - (i + 1) * 5 * 24 * 3600 * 1000).toISOString(),
  price: [
    29990000, 26990000, 42000000, 7490000, 11990000, 21990000, 3200000, 499000, 850000, 2100000,
    1890000, 95000,
  ][i],
}));

export const MOCK_SELLER_CAMPAIGNS = [
  {
    id: 'sc-1',
    name: 'Flash Sale Tháng 6',
    status: 'ACTIVE',
    budget: 10000000,
    spent: 6800000,
    impressions: 248000,
    clicks: 9840,
    ctr: 3.97,
    roas: 11.2,
    startsAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'sc-2',
    name: 'Quảng cáo iPhone 15',
    status: 'ACTIVE',
    budget: 20000000,
    spent: 14200000,
    impressions: 580000,
    clicks: 18400,
    ctr: 3.17,
    roas: 8.9,
    startsAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 20 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'sc-3',
    name: 'Apple Watch Sale',
    status: 'PAUSED',
    budget: 5000000,
    spent: 3200000,
    impressions: 124000,
    clicks: 3980,
    ctr: 3.21,
    roas: 6.4,
    startsAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 10 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'sc-4',
    name: 'iPad Pro Launch',
    status: 'DRAFT',
    budget: 15000000,
    spent: 0,
    impressions: 0,
    clicks: 0,
    ctr: 0,
    roas: 0,
    startsAt: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 32 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_SELLER_DISPUTES = [
  {
    id: 'sdisp-1',
    orderId: 'ord-001',
    buyerName: 'Nguyễn Văn A',
    reason: 'Sản phẩm không đúng mô tả - màu sắc khác',
    status: 'OPEN',
    amount: 29990000,
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    deadline: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'sdisp-2',
    orderId: 'ord-002',
    buyerName: 'Trần Thị B',
    reason: 'Hàng bị hỏng khi giao',
    status: 'RESPONDED',
    amount: 7490000,
    createdAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    deadline: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'sdisp-3',
    orderId: 'ord-003',
    buyerName: 'Lê Văn C',
    reason: 'Giao hàng chậm hơn cam kết',
    status: 'RESOLVED',
    amount: 3200000,
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    deadline: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_SELLER_SUBSCRIPTION = {
  current: {
    planId: 'plan-professional',
    planName: 'Professional',
    price: 2990000,
    billingCycle: 'MONTHLY',
    status: 'ACTIVE',
    nextBillingAt: new Date(Date.now() + 18 * 24 * 3600 * 1000).toISOString(),
    cancelAt: null,
  },
  plans: [
    {
      id: 'plan-free',
      name: 'Free',
      price: 0,
      billingCycle: 'MONTHLY',
      features: ['100 sản phẩm', '5% hoa hồng', 'Hỗ trợ email'],
      productLimit: 100,
      commissionRate: 5,
    },
    {
      id: 'plan-basic',
      name: 'Basic',
      price: 990000,
      billingCycle: 'MONTHLY',
      features: ['500 sản phẩm', '4% hoa hồng', 'Analytics cơ bản', 'Hỗ trợ chat'],
      productLimit: 500,
      commissionRate: 4,
    },
    {
      id: 'plan-professional',
      name: 'Professional',
      price: 2990000,
      billingCycle: 'MONTHLY',
      features: [
        'Không giới hạn sản phẩm',
        '3% hoa hồng',
        'Analytics nâng cao',
        'Ads tín dụng 500K/tháng',
        'Hỗ trợ ưu tiên',
      ],
      productLimit: -1,
      commissionRate: 3,
    },
    {
      id: 'plan-enterprise',
      name: 'Enterprise',
      price: 9990000,
      billingCycle: 'MONTHLY',
      features: ['Tất cả Professional', '2% hoa hồng', 'API riêng', 'Account manager', 'SLA 99.9%'],
      productLimit: -1,
      commissionRate: 2,
    },
  ],
  invoices: [
    {
      id: 'inv-1',
      amount: 2990000,
      status: 'PAID',
      paidAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
      period: 'Tháng 5/2026',
    },
    {
      id: 'inv-2',
      amount: 2990000,
      status: 'PAID',
      paidAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
      period: 'Tháng 4/2026',
    },
    {
      id: 'inv-3',
      amount: 990000,
      status: 'PAID',
      paidAt: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
      period: 'Tháng 3/2026',
    },
  ],
};

export const MOCK_SELLER_PAYMENTS = Array.from({ length: 15 }, (_, i) => ({
  id: `spmt-${i + 1}`,
  orderId: `ord-${String(i + 1).padStart(3, '0')}`,
  buyerName: `Khách hàng ${i + 1}`,
  amount: Math.round((500000 + Math.random() * 30000000) / 1000) * 1000,
  commission: Math.round(((500000 + Math.random() * 30000000) * 0.03) / 1000) * 1000,
  netAmount: 0,
  status: ['PENDING', 'COMPLETED', 'REFUNDED', 'HELD'][i % 4],
  payoutDate: i < 10 ? new Date(Date.now() + (i + 1) * 3 * 24 * 3600 * 1000).toISOString() : null,
  createdAt: new Date(Date.now() - (i + 1) * 2 * 24 * 3600 * 1000).toISOString(),
})).map((p) => ({ ...p, netAmount: p.amount - p.commission }));

export const MOCK_SELLER_STREAMS = [
  {
    id: 'stream-s1',
    title: 'Flash Sale iPhone 15 Pro MAX - Giảm 15%!',
    status: 'LIVE',
    viewerCount: 12840,
    peakViewers: 15200,
    likes: 4820,
    comments: 1240,
    gifts: 380,
    revenue: 284000000,
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    thumbnailUrl: 'https://placehold.co/400x225/1a1a2e/eee?text=📱+Live+Flash+Sale',
  },
  {
    id: 'stream-s2',
    title: 'Unboxing iPad Pro M2 mới nhất',
    status: 'ENDED',
    viewerCount: 0,
    peakViewers: 8420,
    likes: 2840,
    comments: 680,
    gifts: 180,
    revenue: 124000000,
    startedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    endedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
    thumbnailUrl: 'https://placehold.co/400x225/f8f8f8/333?text=📦+Unboxing+iPad',
  },
  {
    id: 'stream-s3',
    title: 'Review Apple Watch Series 9',
    status: 'ENDED',
    viewerCount: 0,
    peakViewers: 5280,
    likes: 1840,
    comments: 420,
    gifts: 95,
    revenue: 52000000,
    startedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    endedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000 + 90 * 60 * 1000).toISOString(),
    thumbnailUrl: 'https://placehold.co/400x225/e8f4fd/333?text=⌚+Apple+Watch',
  },
];

// ── Admin analytics mock data ─────────────────────────────────

export const MOCK_ADMIN_GMV = {
  daily: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 3600 * 1000).toLocaleDateString('vi-VN', {
      month: 'short',
      day: 'numeric',
    }),
    gmv: Math.round((800000000 + Math.random() * 400000000) / 1000) * 1000,
    orders: Math.floor(1200 + Math.random() * 600),
    aov: Math.round(600000 + Math.random() * 200000),
  })),
  categoryBreakdown: [
    { category: 'Điện thoại', gmv: 18400000000, orders: 24800, share: 28.4 },
    { category: 'Laptop', gmv: 12200000000, orders: 8400, share: 18.8 },
    { category: 'Thời trang', gmv: 8400000000, orders: 84000, share: 12.9 },
    { category: 'Làm đẹp', gmv: 6800000000, orders: 48000, share: 10.5 },
    { category: 'Âm thanh', gmv: 5200000000, orders: 18400, share: 8.0 },
    { category: 'Giày dép', gmv: 4800000000, orders: 36000, share: 7.4 },
    { category: 'Đồng hồ', gmv: 3600000000, orders: 12400, share: 5.5 },
    { category: 'Khác', gmv: 5500000000, orders: 84000, share: 8.5 },
  ],
  orderFunnel: [
    { step: 'Xem trang sản phẩm', count: 4820000, pct: 100 },
    { step: 'Thêm vào giỏ hàng', count: 1248000, pct: 25.9 },
    { step: 'Bắt đầu checkout', count: 624000, pct: 12.9 },
    { step: 'Nhập thông tin', count: 498000, pct: 10.3 },
    { step: 'Chọn thanh toán', count: 456000, pct: 9.5 },
    { step: 'Hoàn thành đơn', count: 382000, pct: 7.9 },
  ],
  hourlyThroughput: Array.from({ length: 48 }, (_, i) => ({
    hour: new Date(Date.now() - (47 - i) * 3600 * 1000).toLocaleTimeString('vi-VN', {
      hour: '2-digit',
      minute: '2-digit',
    }),
    orders: Math.floor(20 + Math.random() * 180),
  })),
  summary: {
    totalGMV: 64900000000,
    gmvGrowth: 18.4,
    totalOrders: 316000,
    ordersGrowth: 12.1,
    aov: 205380,
    cancelRate: 2.8,
  },
};

export const MOCK_SEARCH_TOP_QUERIES = Array.from({ length: 20 }, (_, i) => ({
  query: [
    'iphone 15',
    'samsung s24',
    'laptop gaming',
    'tai nghe',
    'giày nike',
    'áo thun',
    'son môi',
    'bàn phím cơ',
    'chuột không dây',
    'iPad pro',
    'smartwatch',
    'máy ảnh',
    'loa bluetooth',
    'dép sandal',
    'mỹ phẩm',
    'sách hay',
    'đồ chơi trẻ em',
    'phụ kiện điện thoại',
    'máy lọc không khí',
    'đồng hồ thể thao',
  ][i],
  count: Math.floor(8000 - i * 300 + Math.random() * 500),
  clickRate: +(0.65 - i * 0.02 + Math.random() * 0.05).toFixed(2),
  zeroResultRate: +(0.02 + Math.random() * 0.08).toFixed(2),
  trend: i < 5 ? 'UP' : i < 12 ? 'STABLE' : 'DOWN',
}));

export const MOCK_LIVE_STREAMS = [
  {
    id: 'live-1',
    title: 'Flash Sale iPhone 15 Pro MAX - Giảm 15%!',
    hostName: 'Apple Store VN',
    hostAvatar: 'https://placehold.co/60x60/f5f5f5/333?text=A',
    viewerCount: 12840,
    thumbnailUrl: 'https://placehold.co/400x225/1a1a2e/eee?text=📱+Live+Flash+Sale',
    isLive: true,
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'live-2',
    title: 'Unboxing Samsung S24 Ultra + Tặng quà cho viewer',
    hostName: 'TechReview VN',
    hostAvatar: 'https://placehold.co/60x60/f0f0f8/333?text=T',
    viewerCount: 8420,
    thumbnailUrl: 'https://placehold.co/400x225/0d47a1/eee?text=📦+Unboxing+Live',
    isLive: true,
    startedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'live-3',
    title: 'Thời trang Hè 2026 - Mix & Match cùng Fashion TV',
    hostName: 'Fashion TV VN',
    hostAvatar: 'https://placehold.co/60x60/fce4ec/333?text=F',
    viewerCount: 5280,
    thumbnailUrl: 'https://placehold.co/400x225/880e4f/eee?text=👗+Fashion+Live',
    isLive: true,
    startedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'live-4',
    title: 'Làm đẹp - Review son MAC mới nhất 2026',
    hostName: 'Beauty Guru VN',
    hostAvatar: 'https://placehold.co/60x60/fce4ec/333?text=B',
    viewerCount: 3940,
    thumbnailUrl: 'https://placehold.co/400x225/ad1457/eee?text=💄+Beauty+Live',
    isLive: true,
    startedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
];

export const MOCK_FLASH_SALE_SESSION = {
  id: 'flash-session-1',
  name: 'Flash Sale Hè 2026 — Giảm đến 50%',
  startsAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  endsAt: new Date(Date.now() + 2.5 * 3600 * 1000).toISOString(),
  products: [
    {
      id: 'fs-1',
      name: 'iPhone 15 Pro Max 256GB',
      imageUrl: 'https://placehold.co/400x400/f5f5f5/333?text=iPhone+15+Pro',
      originalPrice: 34990000,
      salePrice: 29990000,
      stock: 5,
      totalSlots: 20,
      soldCount: 15,
    },
    {
      id: 'fs-2',
      name: 'Sony WH-1000XM5',
      imageUrl: 'https://placehold.co/400x400/222/eee?text=Sony+WH-1000XM5',
      originalPrice: 8990000,
      salePrice: 6990000,
      stock: 8,
      totalSlots: 30,
      soldCount: 22,
    },
    {
      id: 'fs-3',
      name: 'Nike Air Max 270',
      imageUrl: 'https://placehold.co/400x400/fff/333?text=Nike+Air+Max',
      originalPrice: 4200000,
      salePrice: 2800000,
      stock: 15,
      totalSlots: 50,
      soldCount: 35,
    },
    {
      id: 'fs-4',
      name: 'Logitech MX Master 3S',
      imageUrl: 'https://placehold.co/400x400/f5f0ff/333?text=MX+Master+3S',
      originalPrice: 2290000,
      salePrice: 1590000,
      stock: 20,
      totalSlots: 40,
      soldCount: 20,
    },
    {
      id: 'fs-5',
      name: 'Áo Thun Uniqlo AIRism',
      imageUrl: 'https://placehold.co/400x400/e8f5e9/333?text=Uniqlo',
      originalPrice: 699000,
      salePrice: 399000,
      stock: 50,
      totalSlots: 100,
      soldCount: 50,
    },
    {
      id: 'fs-6',
      name: 'Bàn phím Keychron K2 Pro',
      imageUrl: 'https://placehold.co/400x400/fafafa/333?text=Keychron+K2',
      originalPrice: 2500000,
      salePrice: 1890000,
      stock: 10,
      totalSlots: 25,
      soldCount: 15,
    },
  ],
};
